# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 13:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=500)),
                ('upc', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('case_pack', models.PositiveIntegerField()),
                ('inner_pack', models.PositiveIntegerField()),
                ('in_stock', models.BooleanField()),
                ('color', models.CharField(max_length=60)),
                ('shape', models.CharField(max_length=60)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
