# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
