# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darice', '0002_product_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
    ]
