# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 00:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darice', '0003_remove_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), size=None),
        ),
    ]
