# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darice', '0004_auto_20180407_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='darice.Product'),
        ),
    ]
